name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main # Ajuste se o branch principal for diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Verificar o código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Use a versão recomendada pelo Angular

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Build do projeto Angular
      - name: Build Angular project
        run: npm run build -- --configuration production

      # Criar o arquivo .nojekyll
      - name: Disable Jekyll
        run: echo "" > dist/nome-do-projeto/.nojekyll

      # Deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs